version = 1
root = "fa42a602-e7c1-4e5c-aaeb-cacdb01a525a"

[[samples]]
id = "fa42a602-e7c1-4e5c-aaeb-cacdb01a525a"
name = "Arrangement"
kind = "arrangement"

[samples.graph]

[samples.trigger]
release = 0.0

[samples.arrangement]
bpm = 110.0
length_secs = 8.0
loop_start = 0.0
loop_end = 8.0

[[samples.arrangement.tracks]]
name = "Bass"
gain = 0.949999988079071

[[samples.arrangement.tracks.gain_automation]]
time = 0.0
gain = 1.0

[[samples.arrangement.tracks.gain_automation]]
time = 4.0
gain = 0.7200000286102295

[[samples.arrangement.tracks.gain_automation]]
time = 6.0
gain = 0.7200000286102295

[[samples.arrangement.tracks.gain_automation]]
time = 8.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 0.0
length = 4.0
source = "c82c6c8a-1d07-4b31-924e-f1401f98c356"
offset = 0.0
gain = 1.0
looping = true
name = "bass A"

[[samples.arrangement.tracks.clips]]
start = 4.0
length = 4.0
source = "c82c6c8a-1d07-4b31-924e-f1401f98c356"
offset = 0.0
gain = 0.800000011920929
looping = true
name = "bass B"

[[samples.arrangement.tracks]]
name = "Kick"
gain = 0.8999999761581421

[[samples.arrangement.tracks.clips]]
start = 0.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0
name = "kick"

[[samples.arrangement.tracks.clips]]
start = 1.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 2.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 3.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 4.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 5.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 6.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 7.0
length = 0.5
source = "92558f4a-d454-4655-9b5e-dcc990597a79"
offset = 0.0
gain = 1.0

[[samples.arrangement.sections]]
name = "A"
start = 0.0
end = 4.0

[[samples.arrangement.sections]]
name = "B"
start = 4.0
end = 8.0

[[samples]]
id = "c82c6c8a-1d07-4b31-924e-f1401f98c356"
name = "Bass"
kind = "sound"

[[samples.graph.nodes]]
id = "07875b2c-68c9-4c58-b530-4222d95547c2"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "8609b81b-de7e-498e-ba77-d24cdac5a063"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 600.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 4.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "89fbec55-d1d8-4e5c-a4c3-b03e1ec0000f"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.699999988079071
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.405

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "07875b2c-68c9-4c58-b530-4222d95547c2"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "8609b81b-de7e-498e-ba77-d24cdac5a063"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "8609b81b-de7e-498e-ba77-d24cdac5a063"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "89fbec55-d1d8-4e5c-a4c3-b03e1ec0000f"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "92558f4a-d454-4655-9b5e-dcc990597a79"
name = "Kick"
kind = "sound"

[[samples.graph.nodes]]
id = "c11d81e5-6725-48b0-bc03-9d8777c1cb07"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 150.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 150.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 50.0
time = 0.12

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "d6f53568-0eae-4941-b8e5-1be349f5293c"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.949999988079071
time = 0.002

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.28200000000000003

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "c11d81e5-6725-48b0-bc03-9d8777c1cb07"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d6f53568-0eae-4941-b8e5-1be349f5293c"
input = 0

[samples.trigger]
release = 0.0

[assets]
