version = 1
root = "aab73202-2502-4faa-b339-47b73c30066a"

[[samples]]
id = "aab73202-2502-4faa-b339-47b73c30066a"
name = "Bell"
kind = "sound"

[[samples.graph.nodes]]
id = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.550000011920929

[[samples.graph.nodes]]
id = "c23f633b-91e3-461c-93c9-a72d9c93b58a"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 246.39999389648438

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "6bd01282-ed2a-449e-b984-ec51445ddf1d"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.5
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 3.204

[[samples.graph.nodes]]
id = "5e2264bf-d9da-4747-aba7-208d154d8c94"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 404.8000183105469

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "7b447b70-b4cb-44cc-ac37-c395eac01939"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.3499999940395355
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 2.604

[[samples.graph.nodes]]
id = "f0c8a4f7-511a-4eb1-883a-441378092894"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 523.6000366210938

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "d5f52b51-9830-4a27-8277-881bb02be899"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.30000001192092896
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 2.204

[[samples.graph.nodes]]
id = "dac1e019-81e4-4677-8c97-87c5a8e901be"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 752.4000244140625

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "af43cea7-51b0-4701-9db4-dbb11c4ca326"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.2199999988079071
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.604

[[samples.graph.nodes]]
id = "d8e2c7ea-0785-4fec-958d-b46d387531e1"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 880.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "d70dcb87-0a6c-49e7-b328-ccf710475108"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.44999998807907104
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 3.004

[[samples.graph.nodes]]
id = "f05e7fae-6f87-4372-87c8-9a635069341c"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 1205.5999755859375

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "5294e5d8-bc7e-4e93-a796-9f3bb0796c23"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.18000000715255737
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.204

[[samples.graph.nodes]]
id = "13d0f1a9-4fdf-45d1-a755-b3cd9760a97e"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 1320.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "000a4d17-8215-4617-8311-2df62122c47c"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.15000000596046448
time = 0.004

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.004

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "c23f633b-91e3-461c-93c9-a72d9c93b58a"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "6bd01282-ed2a-449e-b984-ec51445ddf1d"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "6bd01282-ed2a-449e-b984-ec51445ddf1d"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "5e2264bf-d9da-4747-aba7-208d154d8c94"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "7b447b70-b4cb-44cc-ac37-c395eac01939"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "7b447b70-b4cb-44cc-ac37-c395eac01939"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "f0c8a4f7-511a-4eb1-883a-441378092894"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d5f52b51-9830-4a27-8277-881bb02be899"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d5f52b51-9830-4a27-8277-881bb02be899"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "dac1e019-81e4-4677-8c97-87c5a8e901be"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "af43cea7-51b0-4701-9db4-dbb11c4ca326"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "af43cea7-51b0-4701-9db4-dbb11c4ca326"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d8e2c7ea-0785-4fec-958d-b46d387531e1"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d70dcb87-0a6c-49e7-b328-ccf710475108"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d70dcb87-0a6c-49e7-b328-ccf710475108"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "f05e7fae-6f87-4372-87c8-9a635069341c"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "5294e5d8-bc7e-4e93-a796-9f3bb0796c23"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "5294e5d8-bc7e-4e93-a796-9f3bb0796c23"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "13d0f1a9-4fdf-45d1-a755-b3cd9760a97e"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "000a4d17-8215-4617-8311-2df62122c47c"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "000a4d17-8215-4617-8311-2df62122c47c"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "c10a9e45-8ef9-4447-9b05-5933b1a9614a"
input = 0

[samples.trigger]
release = 0.0

[assets]
