version = 1
root = "cc9ca9e8-2c2d-4ad5-82d4-c2193c9fdd6e"

[[samples]]
id = "cc9ca9e8-2c2d-4ad5-82d4-c2193c9fdd6e"
name = "Crush"
kind = "sound"

[[samples.graph.nodes]]
id = "4f3a051a-b295-432a-8515-c56c8f4345f4"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "d54074ed-dc95-49d6-ae5f-c8b6053d4a0b"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "f2c08804-f607-4a47-a4a8-d824005e3e81"
processor_name = "bitcrusher"

[[samples.graph.nodes.kind.props.parameters]]
name = "bits"
min = 1.0
max = 16.0

[samples.graph.nodes.kind.props.parameters.param]
value = 5.0

[[samples.graph.nodes.kind.props.parameters]]
name = "reduction"
min = 1.0
max = 32.0

[samples.graph.nodes.kind.props.parameters.param]
value = 6.0

[[samples.graph.nodes]]
id = "878dcd7d-1e43-448b-ae3f-f626c4310661"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 3500.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 3500.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 400.0
time = 0.5

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 6.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "05590960-e536-4f0a-a8c4-38aaa869d0bf"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.699999988079071
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.605

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "4f3a051a-b295-432a-8515-c56c8f4345f4"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d54074ed-dc95-49d6-ae5f-c8b6053d4a0b"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d54074ed-dc95-49d6-ae5f-c8b6053d4a0b"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "878dcd7d-1e43-448b-ae3f-f626c4310661"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "878dcd7d-1e43-448b-ae3f-f626c4310661"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "05590960-e536-4f0a-a8c4-38aaa869d0bf"
input = 0

[samples.trigger]
release = 0.0

[[assets.wasm_modules]]
id = "f2c08804-f607-4a47-a4a8-d824005e3e81"
label = "bitcrusher"

[assets.wasm_modules.source]
kind = "base64"
data = "AGFzbQEAAAABTQ5gAn9/AX9gA39/fwF/YAJ/fwBgAAF/YAJ9fwBgAX8BfWABfwBgAX8Bf2AAAGADf39/AGAEf39/fwF/YAR/f39/AGABfQF9YAJ9fQF9AxoZAwQDAwUGBQUHBwMGCAkGAAoCCwgGBgIMDQQFAXABBAQFAwEAEQYZA38BQYCAwAALfwBB4JTAAAt/AEHglMAACwe/AQ8GbWVtb3J5AgAIY2hhbm5lbHMAAARpbml0AAEJaW5wdXRfcHRyAAIKb3V0cHV0X3B0cgADDXBhcmFtX2RlZmF1bHQABAlwYXJhbV9tYXgABglwYXJhbV9taW4ABw5wYXJhbV9uYW1lX2xlbgAIDnBhcmFtX25hbWVfcHRyAAkKcGFyYW1zX3B0cgAKB3Byb2Nlc3MACwtwYXJhbV9jb3VudAAACl9fZGF0YV9lbmQDAQtfX2hlYXBfYmFzZQMCCQkBAEEBCwMPFhEKkRQZBABBAgsjAEEAQgA3AsCDwIAAQQBBATYCvIPAgABBAEIANwLIg8CAAAsIAEHQg8CAAAsIAEHQi8CAAAsiAAJAIABBAUsNACAAQRRsKgKggcCAAA8LIAAQhYCAgAAAC2MCAX8BfiOAgICAAEEgayIBJICAgIAAIAFBAjYCDCABIAA2AgggAUGBgICAAK1CIIYiAiABQQhqrYQ3AxggASACIAFBDGqthDcDEEGAgMCAACABQRBqQeCAwIAAEI2AgIAAAAsiAAJAIABBAUsNACAAQRRsKgKcgcCAAA8LIAAQhYCAgAAACxsAAkAgAEEBSw0AQwAAgD8PCyAAEIWAgIAAAAsiAAJAIABBAUsNACAAQRRsKAKUgcCAAA8LIAAQhYCAgAAACyIAAkAgAEEBSw0AIABBFGwoApCBwIAADwsgABCFgICAAAALCABB0JPAgAALuAUCA30FfwJAQQAoAryDwIAADQBBAEIANwLAg8CAAEEAQQE2AryDwIAAQQBCADcCyIPAgAALQwAAgD8hAQJAQwAAgEFDAACAP0EAKgLQk8CAACICIAJDAACAP10bIgIgAkMAAIBBXhsiAo4iA/wAIgRBAUgNAEMAAIA/IQECQAJAIARBB3EiBQ0AIAQhBQwBCwNAIAEgAZIhASAFQX9qIgUNAAsgBEH4////B3EhBQsgBEEISQ0AIAVBCGohBQNAIAEgAZIiASABkiIBIAGSIgEgAZIiASABkiIBIAGSIgEgAZIiASABkiEBIAVBeGoiBUEISg0ACwsCQAJAQQAqAtSTwIAAQwAAgD8QmICAgAD8ASIGRQ0AIABFDQEgAEGAASAAQYABSRshBSACIAOTIgIgAkPw/XU+lEMYcjE/kpRDAACAP5IgAZQhAkEAKgLAg8CAACEDQQAoAsiDwIAAIQdB0IPAgAAhCEHQi8CAACEAQQAhBANAQwAAAD8hAQJAIAQgBU8NACAIKgIAQwAAAD+UQwAAAD+SIQELAkAgByAEaiAGcA0AQQAgAiABlBCXgICAACAClSIBIAGSQwAAgL+SIgM4AsCDwIAACyAAIAM4AgAgAEEEaiEAIAhBBGohCCAFIARBAWoiBEcNAAtBACAHIAVqNgLIg8CAAEEAKgLEg8CAACEDQQAoAsyDwIAAIQhBgAQhAEEAIQQDQEMAAAA/IQECQCAEIAVPDQAgAEHQg8CAAGoqAgBDAAAAP5RDAAAAP5IhAQsCQCAIIARqIAZwDQBBACACIAGUEJeAgIAAIAKVIgEgAZJDAACAv5IiAzgCxIPAgAALIABB0IvAgABqIAM4AgAgAEEEaiEAIAUgBEEBaiIERw0AC0EAIAggBWo2AsyDwIAADAELIABFDQAQjICAgAAACwsYAEGAg8CAAEHzAEHwgMCAABCNgICAAAALRwEBfyOAgICAAEEgayIDJICAgIAAIAMgATYCECADIAA2AgwgA0EBOwEcIAMgAjYCGCADIANBDGo2AhQgA0EUahCOgICAAAALOAIBfwF+I4CAgIAAQRBrIgEkgICAgAAgACkCACECIAEgADYCDCABIAI3AgQgAUEEahCUgICAAAAL4gYCC38BfiOAgICAAEEQayICJICAgIAAQQohAyAAKAIAIgQhBQJAIARB6AdJDQBBCiEDIAQhBQNAIAJBBmogA2oiBkF8aiAFIgAgAEGQzgBuIgVBkM4AbGsiB0H//wNxQeQAbiIIQQF0LwC4gcCAADsAACAGQX5qIAcgCEHkAGxrQf//A3FBAXQvALiBwIAAOwAAIANBfGohAyAAQf+s4gRLDQALCwJAAkAgBUEJSw0AIAUhAAwBCyACQQZqIANBfmoiA2ogBSAFQf//A3FB5ABuIgBB5ABsa0H//wNxQQF0LwC4gcCAADsAAAsCQAJAIARFDQAgAEUNAQsgAkEGaiADQX9qIgNqIABBAXQtALmBwIAAOgAAC0ErQYCAxAAgASgCCCIAQYCAgAFxIgUbIQQgAEGAgIAEcUEXdiEJIAJBBmogA2ohCgJAAkAgBUEVdkEKIANrIgtqIgcgAS8BDCIITw0AAkACQAJAIABBgICACHENACAIIAdrIQxBACEDQQAhCAJAAkACQCAAQR12QQNxDgQCAAEAAgsgDCEIDAELIAxB/v8DcUEBdiEICyAAQf///wBxIQcgASgCBCEGIAEoAgAhBQNAIANB//8DcSAIQf//A3FPDQJBASEAIANBAWohAyAFIAcgBigCEBGAgICAAICAgIAARQ0ADAULCyABIAEpAggiDadBgICA/3lxQbCAgIACcjYCCEEBIQAgASgCACIFIAEoAgQiBiAEIAkQkICAgAANA0EAIQMgCCAHa0H//wNxIQcDQCADQf//A3EgB08NAkEBIQAgA0EBaiEDIAVBMCAGKAIQEYCAgIAAgICAgABFDQAMBAsLQQEhACAFIAYgBCAJEJCAgIAADQIgBSAKIAsgBigCDBGBgICAAICAgIAADQIgDCAIa0H//wNxIQhBACEDA0ACQCADQf//A3EgCEkNAEEAIQAMBAtBASEAIANBAWohAyAFIAcgBigCEBGAgICAAICAgIAARQ0ADAMLC0EBIQAgBSAKIAsgBigCDBGBgICAAICAgIAADQEgASANNwIIQQAhAAwBC0EBIQAgASgCACIDIAEoAgQiBSAEIAkQkICAgAANACADIAogCyAFKAIMEYGAgIAAgICAgAAhAAsgAkEQaiSAgICAACAAC0kAAkAgAkGAgMQARg0AIAAgAiABKAIQEYCAgIAAgICAgABFDQBBAQ8LAkAgAw0AQQAPCyAAIANBACABKAIMEYGAgIAAgICAgAALCQAgAEEANgIAC5kBAQJ/I4CAgIAAQRBrIgQkgICAgABBAEEAKALclMCAACIFQQFqNgLclMCAAAJAIAVBAEgNAAJAAkBBAC0A1JTAgAANAEEAQQAoAtCUwIAAQQFqNgLQlMCAAEEAKALYlMCAAEF/Sg0BDAILIARBCGogACABEYKAgIAAgICAgAAAC0EAQQA6ANSUwIAAIAJFDQAQk4CAgAAACwALAwAACwsAIAAQlYCAgAAAC5ABAQN/I4CAgIAAQRBrIgEkgICAgAACQCAAKAIAIgIoAgQiA0EBcUUNACACKAIAIQIgASADQQF2NgIEIAEgAjYCACABQYKAgIAAIAAoAggiAC0ACCAALQAJEJKAgIAAAAsgAUGAgICAeDYCACABIAA2AgwgAUGDgICAACAAKAIIIgAtAAggAC0ACRCSgICAAAALDAAgACABKQIANwMAC1QBAn8CQCAAQ////z4gAJiSIgC8IgFBF3ZB/wFxIgJBlQFLDQBBgICAgHhBgICAfCACQYF/anUgAkH/AEkbIgJBf3MgAXFFDQAgAiABcb4hAAsgAAsUACABIAEgACAAIAFdGyAAIABcGwsLwwMBAEGAgMAAC7kDIGluZGV4IG91dCBvZiBib3VuZHM6IHRoZSBsZW4gaXMgwBIgYnV0IHRoZSBpbmRleCBpcyDAAHBhY2thZ2VzL3dvcmtsZXRzL2JpdGNydXNoZXIvc3JjL2xpYi5ycwAANwAQACcAAABIAAAAAQAAADcAEAAnAAAALAAAABQAAABiaXRzcmVkdWN0aW9uAAAAgAAQAAQAAAAAAIA/AACAQQAAwECEABAACQAAAAAAgD8AAABCAACAQDAwMDEwMjAzMDQwNTA2MDcwODA5MTAxMTEyMTMxNDE1MTYxNzE4MTkyMDIxMjIyMzI0MjUyNjI3MjgyOTMwMzEzMjMzMzQzNTM2MzczODM5NDA0MTQyNDM0NDQ1NDY0NzQ4NDk1MDUxNTI1MzU0NTU1NjU3NTg1OTYwNjE2MjYzNjQ2NTY2Njc2ODY5NzA3MTcyNzM3NDc1NzY3Nzc4Nzk4MDgxODI4Mzg0ODU4Njg3ODg4OTkwOTE5MjkzOTQ5NTk2OTc5ODk5YXR0ZW1wdCB0byBjYWxjdWxhdGUgdGhlIHJlbWFpbmRlciB3aXRoIGEgZGl2aXNvciBvZiB6ZXJvANUIBG5hbWUAIyJhd3NtX2F1ZGlvX3dvcmtsZXRfYml0Y3J1c2hlci53YXNtAYgIGQAIY2hhbm5lbHMBBGluaXQCCWlucHV0X3B0cgMKb3V0cHV0X3B0cgQNcGFyYW1fZGVmYXVsdAU3X1JOdk50Q3NnWEdwNU9xeDJOeV80Y29yZTlwYW5pY2tpbmcxOHBhbmljX2JvdW5kc19jaGVjawYJcGFyYW1fbWF4BwlwYXJhbV9taW4IDnBhcmFtX25hbWVfbGVuCQ5wYXJhbV9uYW1lX3B0cgoKcGFyYW1zX3B0cgsHcHJvY2VzcwxLX1JOdk50TnRDc2dYR3A1T3F4Mk55XzRjb3JlOXBhbmlja2luZzExcGFuaWNfY29uc3QyM3BhbmljX2NvbnN0X3JlbV9ieV96ZXJvDS1fUk52TnRDc2dYR3A1T3F4Mk55XzRjb3JlOXBhbmlja2luZzlwYW5pY19mbXQOLl9STnZDc2ZMZnk2RUkxNWlMXzdfX19ydXN0YzE3cnVzdF9iZWdpbl91bndpbmQPP19STnZYc2lfTnROdE50Q3NnWEdwNU9xeDJOeV80Y29yZTNmbXQzbnVtM2ltcGpOdEI5XzdEaXNwbGF5M2ZtdBBOX1JOdk52TXNhX050Q3NnWEdwNU9xeDJOeV80Y29yZTNmbXROdEI3XzlGb3JtYXR0ZXIxMnBhZF9pbnRlZ3JhbDEyd3JpdGVfcHJlZml4EXVfUk52WUlOdE52TnRDc2ViSGNhZW9Tcnh5XzNzdGQ5cGFuaWNraW5nMTFiZWdpbl9wYW5pYzdQYXlsb2FkUmVFTnROdENzZ1hHcDVPcXgyTnlfNGNvcmU1cGFuaWMxMlBhbmljUGF5bG9hZDZhc19zdHJCOV8SM19STnZOdENzZWJIY2Flb1NyeHlfM3N0ZDlwYW5pY2tpbmcxNXBhbmljX3dpdGhfaG9vaxMnX1JOdkNzZkxmeTZFSTE1aUxfN19fX3J1c3RjMTBydXN0X3BhbmljFG5fUklOdk50TnRDc2ViSGNhZW9Tcnh5XzNzdGQzc3lzOWJhY2t0cmFjZTI2X19fcnVzdF9lbmRfc2hvcnRfYmFja3RyYWNlTkNOdk50QjZfOXBhbmlja2luZzEzcGFuaWNfaGFuZGxlcjB6RUI2XxU3X1JOQ052TnRDc2ViSGNhZW9Tcnh5XzNzdGQ5cGFuaWNraW5nMTNwYW5pY19oYW5kbGVyMEI1XxaAAV9STnZYczFfTnZOdENzZWJIY2Flb1NyeHlfM3N0ZDlwYW5pY2tpbmcxM3BhbmljX2hhbmRsZXJOdEI1XzE2U3RhdGljU3RyUGF5bG9hZE50TnRDc2dYR3A1T3F4Mk55XzRjb3JlNXBhbmljMTJQYW5pY1BheWxvYWQ2YXNfc3RyFwZyb3VuZGYYBWZtYXhmBxIBAA9fX3N0YWNrX3BvaW50ZXIJCgEABy5yb2RhdGEATQlwcm9kdWNlcnMCCGxhbmd1YWdlAQRSdXN0AAxwcm9jZXNzZWQtYnkBBXJ1c3RjHTEuOTUuMCAoNTk4MDc2MTZlIDIwMjYtMDQtMTQpAJQBD3RhcmdldF9mZWF0dXJlcwgrC2J1bGstbWVtb3J5Kw9idWxrLW1lbW9yeS1vcHQrFmNhbGwtaW5kaXJlY3Qtb3ZlcmxvbmcrCm11bHRpdmFsdWUrD211dGFibGUtZ2xvYmFscysTbm9udHJhcHBpbmctZnB0b2ludCsPcmVmZXJlbmNlLXR5cGVzKwhzaWduLWV4dA=="
