version = 1
root = "da9ce148-9787-47ff-82af-60715e79b6da"

[[samples]]
id = "da9ce148-9787-47ff-82af-60715e79b6da"
name = "Fire"
kind = "sound"

[[samples.graph.nodes]]
id = "aae64dc6-3dc9-4bc5-b513-60bd2f006705"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.8999999761581421

[[samples.graph.nodes]]
id = "ae216573-80b3-4e3b-81a5-799afc1e96a2"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "brown"
seed = 7
seconds = 3.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "dff5fadd-69ab-4e74-9827-b81bd496d45e"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 420.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.6000000238418579

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "14805c7f-bb0c-420b-90a4-d94de1967045"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.550000011920929

[[samples.graph.nodes]]
id = "a1b6dc3f-2348-43dd-9f65-4ece0e2f4df5"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "dust"
seed = 99
seconds = 3.0
stereo = true
density = 220.0
gaussian = false

[[samples.graph.nodes]]
id = "249480d1-4e8b-40b4-be20-5119248a4b37"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "bandpass"

[samples.graph.nodes.kind.props.frequency]
value = 1800.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 3.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "b021009c-a29d-42a0-b4fb-91c1d0794d87"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.699999988079071

[[samples.graph.nodes]]
id = "bfa3970d-a2ed-47f4-9b9f-f8559827a3b3"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "white"
seed = 55
seconds = 3.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "9a009779-26ca-4c9b-acff-05e372962c34"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "highpass"

[samples.graph.nodes.kind.props.frequency]
value = 3000.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.699999988079071

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "d4bef0ce-4fe1-4c81-a1d5-a50eccd6469d"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.07999999821186066

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "ae216573-80b3-4e3b-81a5-799afc1e96a2"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "dff5fadd-69ab-4e74-9827-b81bd496d45e"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "dff5fadd-69ab-4e74-9827-b81bd496d45e"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "14805c7f-bb0c-420b-90a4-d94de1967045"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "14805c7f-bb0c-420b-90a4-d94de1967045"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "aae64dc6-3dc9-4bc5-b513-60bd2f006705"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "a1b6dc3f-2348-43dd-9f65-4ece0e2f4df5"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "249480d1-4e8b-40b4-be20-5119248a4b37"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "249480d1-4e8b-40b4-be20-5119248a4b37"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "b021009c-a29d-42a0-b4fb-91c1d0794d87"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "b021009c-a29d-42a0-b4fb-91c1d0794d87"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "aae64dc6-3dc9-4bc5-b513-60bd2f006705"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "bfa3970d-a2ed-47f4-9b9f-f8559827a3b3"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "9a009779-26ca-4c9b-acff-05e372962c34"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "9a009779-26ca-4c9b-acff-05e372962c34"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d4bef0ce-4fe1-4c81-a1d5-a50eccd6469d"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d4bef0ce-4fe1-4c81-a1d5-a50eccd6469d"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "aae64dc6-3dc9-4bc5-b513-60bd2f006705"
input = 0

[samples.trigger]
release = 0.0

[assets]
