version = 1
root = "ce1e221f-b3d8-47f3-a9a2-3424fe8d979e"

[[samples]]
id = "ce1e221f-b3d8-47f3-a9a2-3424fe8d979e"
name = "Hi-hat"
kind = "sound"

[[samples.graph.nodes]]
id = "40afda9b-f405-4f5e-90eb-82422c40fffd"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "white"
seed = 5
seconds = 1.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "220b4304-0f79-4911-91c0-eeebdcf7e494"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "highpass"

[samples.graph.nodes.kind.props.frequency]
value = 7000.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.800000011920929

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "d99e2651-6d44-479f-90f5-c5e8bbf3969e"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.699999988079071
time = 0.001

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.061

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "40afda9b-f405-4f5e-90eb-82422c40fffd"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "220b4304-0f79-4911-91c0-eeebdcf7e494"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "220b4304-0f79-4911-91c0-eeebdcf7e494"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d99e2651-6d44-479f-90f5-c5e8bbf3969e"
input = 0

[samples.trigger]
release = 0.0

[assets]
