version = 1
root = "a5e5a1f1-3951-4809-9bb5-186f258bea4d"

[[samples]]
id = "a5e5a1f1-3951-4809-9bb5-186f258bea4d"
name = "Kick"
kind = "sound"

[[samples.graph.nodes]]
id = "f8dfed00-8592-4b4b-b467-ae2befebb85a"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 150.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 150.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 50.0
time = 0.12

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "0787f1fa-c273-4285-a38f-28d0b31c72ea"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.949999988079071
time = 0.002

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.28200000000000003

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "f8dfed00-8592-4b4b-b467-ae2befebb85a"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "0787f1fa-c273-4285-a38f-28d0b31c72ea"
input = 0

[samples.trigger]
release = 0.0

[assets]
