version = 1
root = "41ed5e35-f764-425d-8b1e-44641d2a9026"

[[samples]]
id = "41ed5e35-f764-425d-8b1e-44641d2a9026"
name = "Laser"
kind = "sound"

[[samples.graph.nodes]]
id = "16eb2a92-6798-4628-ad34-628925f0be33"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.44999998807907104
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.385

[[samples.graph.nodes]]
id = "a3ce50ae-19a5-4155-9e6c-50663f4131e9"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 3500.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 4.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "01c52773-52ed-42e3-8c4e-09e68a7b6c57"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 1800.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 1800.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 120.0
time = 0.35

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "16e1a621-62c2-4939-be51-d8ff635fcbe8"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "square"

[samples.graph.nodes.kind.props.frequency]
value = 900.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 900.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 80.0
time = 0.35

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "a3ce50ae-19a5-4155-9e6c-50663f4131e9"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "16eb2a92-6798-4628-ad34-628925f0be33"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "01c52773-52ed-42e3-8c4e-09e68a7b6c57"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "a3ce50ae-19a5-4155-9e6c-50663f4131e9"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "16e1a621-62c2-4939-be51-d8ff635fcbe8"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "a3ce50ae-19a5-4155-9e6c-50663f4131e9"
input = 0

[samples.trigger]
release = 0.0

[assets]
