version = 1
root = "1e304a4f-f362-4041-8744-05c1c94e3cae"

[[samples]]
id = "1e304a4f-f362-4041-8744-05c1c94e3cae"
name = "Nested"
kind = "sound"

[[samples.graph.nodes]]
id = "6affb394-f5e6-4dab-ba13-22551d8412e0"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "172ba286-4e23-4245-ab23-77410d03de58"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "a8d66bfe-e1ab-47fb-b763-096b9a2b1e6a"

[[samples.graph.nodes]]
id = "3713a9c1-b7d9-4642-88f8-85793cf5c36a"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "6affb394-f5e6-4dab-ba13-22551d8412e0"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "172ba286-4e23-4245-ab23-77410d03de58"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "172ba286-4e23-4245-ab23-77410d03de58"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "3713a9c1-b7d9-4642-88f8-85793cf5c36a"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "a8d66bfe-e1ab-47fb-b763-096b9a2b1e6a"
name = "Voice"
kind = "sound"

[[samples.graph.nodes]]
id = "776d188f-bb96-4e87-9430-611eaf221be6"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 800.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 1.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "inlet"
port = "in"

[samples.graph.connections.to]
to = "node_input"
node = "776d188f-bb96-4e87-9430-611eaf221be6"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "776d188f-bb96-4e87-9430-611eaf221be6"
output = 0

[samples.graph.connections.to]
to = "outlet"
port = "out"

[[samples.graph.inlets]]
id = "in"

[[samples.graph.outlets]]
id = "out"

[samples.trigger]
release = 0.0

[assets]
