version = 1
root = "9494f2f9-bc68-4dd5-8890-75f3a091fdaf"

[[samples]]
id = "9494f2f9-bc68-4dd5-8890-75f3a091fdaf"
name = "Rain"
kind = "sound"

[[samples.graph.nodes]]
id = "0e060236-46e0-4f63-85e2-82dd4fb40d95"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.8999999761581421

[[samples.graph.nodes]]
id = "d6b88757-bcc9-4c70-8239-a7eb804974fa"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "brown"
seed = 11
seconds = 3.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "7ddf782f-71d6-47dc-b9d9-4975a8d541b1"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 900.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.699999988079071

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "9b967b5b-712a-4b19-9615-7df217216b59"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.nodes]]
id = "480bee14-be92-401c-94c6-9ad22fd650f1"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "pink"
seed = 22
seconds = 3.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "900504f1-b5a1-46b3-85ce-dbbf1c1e5745"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "highpass"

[samples.graph.nodes.kind.props.frequency]
value = 2000.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.699999988079071

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "9be08aca-d811-4627-8752-c647779c20f6"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.18000000715255737

[[samples.graph.nodes]]
id = "987ee8e4-de32-434f-8a70-468b39e9d8f4"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "dust"
seed = 33
seconds = 3.0
stereo = true
density = 1200.0
gaussian = false

[[samples.graph.nodes]]
id = "dd443bc6-4e75-4257-a94a-34361126398a"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "bandpass"

[samples.graph.nodes.kind.props.frequency]
value = 3000.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 1.5

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "aafddcdf-9639-401c-8b25-dd0253a694c7"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d6b88757-bcc9-4c70-8239-a7eb804974fa"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "7ddf782f-71d6-47dc-b9d9-4975a8d541b1"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "7ddf782f-71d6-47dc-b9d9-4975a8d541b1"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "9b967b5b-712a-4b19-9615-7df217216b59"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "9b967b5b-712a-4b19-9615-7df217216b59"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "0e060236-46e0-4f63-85e2-82dd4fb40d95"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "480bee14-be92-401c-94c6-9ad22fd650f1"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "900504f1-b5a1-46b3-85ce-dbbf1c1e5745"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "900504f1-b5a1-46b3-85ce-dbbf1c1e5745"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "9be08aca-d811-4627-8752-c647779c20f6"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "9be08aca-d811-4627-8752-c647779c20f6"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "0e060236-46e0-4f63-85e2-82dd4fb40d95"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "987ee8e4-de32-434f-8a70-468b39e9d8f4"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "dd443bc6-4e75-4257-a94a-34361126398a"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "dd443bc6-4e75-4257-a94a-34361126398a"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "aafddcdf-9639-401c-8b25-dd0253a694c7"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "aafddcdf-9639-401c-8b25-dd0253a694c7"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "0e060236-46e0-4f63-85e2-82dd4fb40d95"
input = 0

[samples.trigger]
release = 0.0

[assets]
