version = 1
root = "6c585f5b-8d76-46c7-9135-866e7f5d063b"

[[samples]]
id = "6c585f5b-8d76-46c7-9135-866e7f5d063b"
name = "Rocket"
kind = "sound"

[[samples.graph.nodes]]
id = "a5030401-91db-42ed-b53a-aa579f414970"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.0
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "linear_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.8999999761581421
time = 4.0

[[samples.graph.nodes]]
id = "074ce2bd-c1af-44ea-b9ab-51ce0980c50e"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "brown"
seed = 3
seconds = 5.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "249b6cdf-049b-40c8-ab6a-ede61877f3d9"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 180.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 180.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "linear_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 6000.0
time = 5.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 1.2000000476837158

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "72a08702-efbc-4f20-ae40-5ff541c409c3"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 38.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 38.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "linear_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 120.0
time = 5.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "a9212460-ed26-4c45-af70-14794a113876"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "074ce2bd-c1af-44ea-b9ab-51ce0980c50e"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "249b6cdf-049b-40c8-ab6a-ede61877f3d9"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "249b6cdf-049b-40c8-ab6a-ede61877f3d9"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "a5030401-91db-42ed-b53a-aa579f414970"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "72a08702-efbc-4f20-ae40-5ff541c409c3"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "a9212460-ed26-4c45-af70-14794a113876"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "a9212460-ed26-4c45-af70-14794a113876"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "a5030401-91db-42ed-b53a-aa579f414970"
input = 0

[samples.trigger]
release = 0.0

[assets]
