version = 1
root = "6acd3f95-ffa5-4b3f-b0a0-c3119a132343"

[[samples]]
id = "6acd3f95-ffa5-4b3f-b0a0-c3119a132343"
name = "Siren"
kind = "sound"

[[samples.graph.nodes]]
id = "0878b681-4ab9-4a9a-92f4-477e44c20259"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 600.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "174eca95-7f6a-49ca-84ec-3114ad4445f4"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.30000001192092896

[[samples.graph.nodes]]
id = "d231990c-6690-4671-9365-7cb369f05094"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "triangle"

[samples.graph.nodes.kind.props.frequency]
value = 0.5

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "49ba83b4-1ee1-47cf-bb90-4651f422ddb8"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 250.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "0878b681-4ab9-4a9a-92f4-477e44c20259"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "174eca95-7f6a-49ca-84ec-3114ad4445f4"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d231990c-6690-4671-9365-7cb369f05094"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "49ba83b4-1ee1-47cf-bb90-4651f422ddb8"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "49ba83b4-1ee1-47cf-bb90-4651f422ddb8"
output = 0

[samples.graph.connections.to]
to = "node_param"
node = "0878b681-4ab9-4a9a-92f4-477e44c20259"
param = "frequency"

[samples.trigger]
release = 0.0

[assets]
