version = 1
root = "a49ffe1d-058c-4a5b-93c0-bebc829dc8ed"

[[samples]]
id = "a49ffe1d-058c-4a5b-93c0-bebc829dc8ed"
name = "Sequenced Song"
kind = "arrangement"

[samples.graph]

[samples.trigger]
release = 0.0

[samples.arrangement]
bpm = 110.0
length_secs = 16.0
loop_start = 0.0
loop_end = 16.0

[[samples.arrangement.tracks]]
name = "Sequenced loop"
gain = 1.0

[[samples.arrangement.tracks.gain_automation]]
time = 0.0
gain = 1.0

[[samples.arrangement.tracks.gain_automation]]
time = 8.0
gain = 0.7200000286102295

[[samples.arrangement.tracks.gain_automation]]
time = 12.0
gain = 0.7200000286102295

[[samples.arrangement.tracks.gain_automation]]
time = 16.0
gain = 1.0

[[samples.arrangement.tracks.clips]]
start = 0.0
length = 4.0
source = "2dc46570-1a0c-46ff-b634-c60c726c363d"
offset = 0.0
gain = 1.0
looping = true
name = "main loop"

[[samples.arrangement.tracks.clips]]
start = 4.0
length = 4.0
source = "2dc46570-1a0c-46ff-b634-c60c726c363d"
offset = 0.0
gain = 1.0
looping = true
name = "Sequenced Loop"

[[samples.arrangement.tracks.clips]]
start = 8.0
length = 4.0
source = "2dc46570-1a0c-46ff-b634-c60c726c363d"
offset = 0.0
gain = 1.0
looping = true
name = "Sequenced Loop"

[[samples.arrangement.tracks.clips]]
start = 12.0
length = 4.0
source = "2dc46570-1a0c-46ff-b634-c60c726c363d"
offset = 0.0
gain = 1.0
looping = true
name = "Sequenced Loop"

[[samples.arrangement.sections]]
name = "A"
start = 0.0
end = 8.0

[[samples.arrangement.sections]]
name = "B breakdown"
start = 8.0
end = 16.0

[[samples]]
id = "2dc46570-1a0c-46ff-b634-c60c726c363d"
name = "Sequenced Loop"
kind = "sound"

[[samples.graph.nodes]]
id = "65d7361b-f762-444e-9729-6f2c103c7029"

[samples.graph.nodes.kind]
kind = "note_sequencer"

[samples.graph.nodes.kind.props]
mode = "melodic"
length = 8.0
looping = true

[samples.graph.nodes.kind.props.song]
bpm = 110.0

[[samples.graph.nodes.kind.props.song.tracks]]
name = "Bass"
channel = 0

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 0.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 1.0
length = 0.45
note = 36
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 1.5
length = 0.45
note = 43
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 2.0
length = 0.45
note = 41
velocity = 100

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 3.0
length = 0.45
note = 39
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 4.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 5.0
length = 0.45
note = 36
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 5.5
length = 0.45
note = 43
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 6.0
length = 0.45
note = 41
velocity = 100

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 7.0
length = 0.45
note = 31
velocity = 95

[[samples.graph.nodes.kind.props.outputs]]
key = "t0"
track = 0
label = "Bass"
gain = 1.0

[[samples.graph.nodes]]
id = "425add69-8d09-4d49-99fd-ab6f51284cd1"

[samples.graph.nodes.kind]
kind = "note_sequencer"

[samples.graph.nodes.kind.props]
mode = "drum"
length = 8.0
looping = true

[samples.graph.nodes.kind.props.song]
bpm = 110.0

[[samples.graph.nodes.kind.props.song.tracks]]
name = "Drums"
channel = 9

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 0.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 0.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 0.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 1.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 1.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 1.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 2.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 2.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 2.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 3.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 3.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 3.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 4.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 4.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 4.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 5.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 5.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 5.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 6.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 6.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 6.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 7.0
length = 0.45
note = 36
velocity = 110

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 7.5
length = 0.45
note = 42
velocity = 70

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 7.0
length = 0.45
note = 42
velocity = 90

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 2.0
length = 0.45
note = 38
velocity = 100

[[samples.graph.nodes.kind.props.song.tracks.events]]
start = 6.0
length = 0.45
note = 38
velocity = 100

[[samples.graph.nodes.kind.props.outputs]]
key = "t0:n36"
track = 0
note = 36
label = "Kick"
gain = 1.0

[[samples.graph.nodes.kind.props.outputs]]
key = "t0:n38"
track = 0
note = 38
label = "Snare"
gain = 1.0

[[samples.graph.nodes.kind.props.outputs]]
key = "t0:n42"
track = 0
note = 42
label = "Hat"
gain = 1.0

[[samples.graph.nodes]]
id = "ab606440-0a73-46df-aa1f-6e4568b9d938"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "1a9539c0-d2ce-4c9c-94ba-d0002e49c08d"

[[samples.graph.nodes]]
id = "f7885f34-9ce3-4e54-a2d3-520311d4dfb3"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "1844892e-23ba-4696-b479-ce816cd735cf"

[[samples.graph.nodes]]
id = "3371f0d3-0ca6-4aff-a677-47c0fda0fc2a"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "6a4a3894-c7ee-421e-8f3a-f5fd2886c19e"

[[samples.graph.nodes]]
id = "d528e7a4-f557-4152-a194-e105b2486eb6"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "ffabf3f6-ea63-4b1d-8972-8bf2aa7c341e"

[[samples.graph.nodes]]
id = "49b83eaf-45aa-4d24-b712-b40b7e79e8fb"

[samples.graph.nodes.kind]
kind = "bus"

[samples.graph.nodes.kind.props]
gain = 0.800000011920929

[[samples.graph.nodes]]
id = "af24341b-9a0e-4d04-a712-1b5deea7d1fc"

[samples.graph.nodes.kind]
kind = "output"

[samples.graph.nodes.kind.props.gain]
value = 1.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "seq_out"
node = "65d7361b-f762-444e-9729-6f2c103c7029"
key = "t0"

[samples.graph.connections.to]
to = "trigger"
node = "ab606440-0a73-46df-aa1f-6e4568b9d938"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "seq_out"
node = "425add69-8d09-4d49-99fd-ab6f51284cd1"
key = "t0:n36"

[samples.graph.connections.to]
to = "trigger"
node = "f7885f34-9ce3-4e54-a2d3-520311d4dfb3"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "seq_out"
node = "425add69-8d09-4d49-99fd-ab6f51284cd1"
key = "t0:n38"

[samples.graph.connections.to]
to = "trigger"
node = "3371f0d3-0ca6-4aff-a677-47c0fda0fc2a"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "seq_out"
node = "425add69-8d09-4d49-99fd-ab6f51284cd1"
key = "t0:n42"

[samples.graph.connections.to]
to = "trigger"
node = "d528e7a4-f557-4152-a194-e105b2486eb6"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "ab606440-0a73-46df-aa1f-6e4568b9d938"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "49b83eaf-45aa-4d24-b712-b40b7e79e8fb"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "f7885f34-9ce3-4e54-a2d3-520311d4dfb3"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "49b83eaf-45aa-4d24-b712-b40b7e79e8fb"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "3371f0d3-0ca6-4aff-a677-47c0fda0fc2a"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "49b83eaf-45aa-4d24-b712-b40b7e79e8fb"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d528e7a4-f557-4152-a194-e105b2486eb6"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "49b83eaf-45aa-4d24-b712-b40b7e79e8fb"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "49b83eaf-45aa-4d24-b712-b40b7e79e8fb"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "af24341b-9a0e-4d04-a712-1b5deea7d1fc"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "1a9539c0-d2ce-4c9c-94ba-d0002e49c08d"
name = "Bass"
kind = "sound"

[[samples.graph.nodes]]
id = "9e9c3379-4ee0-4e07-bf56-8a17918fe1f9"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 261.6300048828125

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "e96bf5c2-01f4-4829-92bb-3391dd03e93c"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 600.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 4.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "b1f54b62-ddd6-42bb-89c6-cec5280a24cf"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.699999988079071
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.355

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "9e9c3379-4ee0-4e07-bf56-8a17918fe1f9"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "e96bf5c2-01f4-4829-92bb-3391dd03e93c"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "e96bf5c2-01f4-4829-92bb-3391dd03e93c"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "b1f54b62-ddd6-42bb-89c6-cec5280a24cf"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "1844892e-23ba-4696-b479-ce816cd735cf"
name = "Kick"
kind = "sound"

[[samples.graph.nodes]]
id = "67d03778-4deb-4959-b0bc-d3a5e872bf87"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 150.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 150.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 50.0
time = 0.12

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "90494f6b-24fa-44f2-89c7-c4d26c36e4c6"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.949999988079071
time = 0.002

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.28200000000000003

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "67d03778-4deb-4959-b0bc-d3a5e872bf87"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "90494f6b-24fa-44f2-89c7-c4d26c36e4c6"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "6a4a3894-c7ee-421e-8f3a-f5fd2886c19e"
name = "Snare"
kind = "sound"

[[samples.graph.nodes]]
id = "1aecc95c-d3db-48ba-8c51-a3961e7598e3"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "white"
seed = 7
seconds = 1.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "4cb00fa4-5fa6-41c2-8f10-e31a2cc9f598"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "highpass"

[samples.graph.nodes.kind.props.frequency]
value = 1500.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.800000011920929

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "14913c23-f2e6-4d70-b069-cb7087d519dd"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.6000000238418579
time = 0.001

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.181

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "1aecc95c-d3db-48ba-8c51-a3961e7598e3"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "4cb00fa4-5fa6-41c2-8f10-e31a2cc9f598"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "4cb00fa4-5fa6-41c2-8f10-e31a2cc9f598"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "14913c23-f2e6-4d70-b069-cb7087d519dd"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "ffabf3f6-ea63-4b1d-8972-8bf2aa7c341e"
name = "Hi-hat"
kind = "sound"

[[samples.graph.nodes]]
id = "4bfc24e9-6762-4ab0-9c72-9ce51f967b40"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "white"
seed = 9
seconds = 1.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "6ea48deb-499a-4926-8f25-87884f841816"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "highpass"

[samples.graph.nodes.kind.props.frequency]
value = 8000.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.800000011920929

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "fa0aab69-6d6b-4f5c-b453-d51819a93acc"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.5
time = 0.001

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.051000000000000004

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "4bfc24e9-6762-4ab0-9c72-9ce51f967b40"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "6ea48deb-499a-4926-8f25-87884f841816"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "6ea48deb-499a-4926-8f25-87884f841816"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "fa0aab69-6d6b-4f5c-b453-d51819a93acc"
input = 0

[samples.trigger]
release = 0.0

[assets]
