version = 1
root = "2ef31091-abf7-489b-9420-9fdc450943c8"

[[samples]]
id = "2ef31091-abf7-489b-9420-9fdc450943c8"
name = "Spatial"
kind = "sound"

[[samples.graph.nodes]]
id = "27e3c86b-6985-4989-a005-693110cf017d"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "triangle"

[samples.graph.nodes.kind.props.frequency]
value = 330.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "8c0d00eb-cd74-4b3a-9ea0-5164aa8945cc"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.nodes]]
id = "12868dbe-b0b5-4f7b-a3ef-d3d96f0e99c3"

[samples.graph.nodes.kind]
kind = "spatial_output"

[samples.graph.nodes.kind.props.gain]
value = 1.0

[samples.graph.nodes.kind.props.position_x]
value = -6.0

[[samples.graph.nodes.kind.props.position_x.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.position_x.automation.args]
value = -6.0
time = 0.0

[[samples.graph.nodes.kind.props.position_x.automation]]
event = "linear_ramp"

[samples.graph.nodes.kind.props.position_x.automation.args]
value = 6.0
time = 4.0

[samples.graph.nodes.kind.props.position_y]
value = 0.0

[samples.graph.nodes.kind.props.position_z]
value = -1.5

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "27e3c86b-6985-4989-a005-693110cf017d"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "8c0d00eb-cd74-4b3a-9ea0-5164aa8945cc"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "8c0d00eb-cd74-4b3a-9ea0-5164aa8945cc"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "12868dbe-b0b5-4f7b-a3ef-d3d96f0e99c3"
input = 0

[samples.trigger]
release = 0.0

[assets]
