version = 1
root = "80c2521e-1558-4b5a-959d-1eb576a80717"

[[samples]]
id = "80c2521e-1558-4b5a-959d-1eb576a80717"
name = "Wind"
kind = "sound"

[[samples.graph.nodes]]
id = "b6fd3b15-0c13-4be3-b842-621982868209"

[samples.graph.nodes.kind]
kind = "noise"

[samples.graph.nodes.kind.props]
flavor = "pink"
seed = 17
seconds = 3.0
stereo = true
density = 0.0
gaussian = false

[[samples.graph.nodes]]
id = "5132b378-9be7-4e6f-bcc6-6be3c0be747d"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "bandpass"

[samples.graph.nodes.kind.props.frequency]
value = 600.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 3.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "14896fe9-3b92-4c37-8013-0148db1868ce"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 1.0

[[samples.graph.nodes]]
id = "928680de-10ff-4b19-ba04-27b0c3898ab6"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 0.15000000596046448

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "5a7d9fe8-5f2e-4571-8b7f-571cbe5352a9"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 450.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "b6fd3b15-0c13-4be3-b842-621982868209"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "5132b378-9be7-4e6f-bcc6-6be3c0be747d"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "5132b378-9be7-4e6f-bcc6-6be3c0be747d"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "14896fe9-3b92-4c37-8013-0148db1868ce"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "928680de-10ff-4b19-ba04-27b0c3898ab6"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "5a7d9fe8-5f2e-4571-8b7f-571cbe5352a9"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "5a7d9fe8-5f2e-4571-8b7f-571cbe5352a9"
output = 0

[samples.graph.connections.to]
to = "node_param"
node = "5132b378-9be7-4e6f-bcc6-6be3c0be747d"
param = "frequency"

[samples.trigger]
release = 0.0

[assets]
